language: python
sudo: true

python:
  - 3.6
  - 3.7
  - 3.8

env:
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.1

before_install:
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
  - gdal-config --prefix
  - gdal-config --libs
  - gdalinfo
  - echo $GDAL_LIBRARY_PATH

install:
  - pip install GDAL-2.2.4-cp36-cp36m-win_amd64
  - pip install -r conf/requirements-dev.txt

before_script:
  - psql -U postgres -c "create extension postgis"

script:
  - coverage run --source='mapwidgets' tests/testapp/manage.py test

after_success:
  - coveralls

addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.4
    - binutils
    - libproj-dev
    - libgdal-dev
    - gdal-bin
    - python-gdal
    - python3-gdal
    - libgeos-dev
    - libyaml-dev
    - libgnutls28-dev

