language: python

python:
  - 2.7
  - 3.6

env:
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.1

matrix:
  exclude:
    - python: 3.6
      env: DJANGO=1.7
    - python: 3.6
      env: DJANGO=1.8
    - python: 3.6
      env: DJANGO=1.9
    - python: 3.6
      env: DJANGO=1.10
    - python: 3.6
      env: DJANGO=1.11
    - python: 3.6
      env: DJANGO=2.0
    - python: 3.6
      env: DJANGO=2.1
cache:
  directories:
  - "$HOME/virtualenv"

install:
  - pip install -r conf/requirements-dev.txt

script:
  - coverage run --source='mapwidgets' tests/testapp/manage.py test

after_success:
  - coveralls

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.4
